
name: Check and Test

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
      - "!gh-pages"
  pull_request:
    branches:
      - "**"

jobs:
  check-should-skip:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - name: Run skip-duplicate-actions
        id: skip_check
        uses: fkirc/skip-duplicate-actions@v5

      - name: Check if is a bump commit
        id: is_bump
        run: |
          if [[ "${{ github.event.head_commit.message }}" == bump:* ]]; then
            echo "is_bump=true" >> $GITHUB_OUTPUT
          else
            echo "is_bump=false" >> $GITHUB_OUTPUT
          fi

      - name: Check if workflow should be skipped
        id: should_skip
        # if is_bump and skip_check all is true, then skip
        run: |
          if [[ ${{ steps.is_bump.outputs.is_bump }} == true || ${{ steps.skip_check.outputs.should_skip }} == true ]]; then
            echo "should_skip=true" >> $GITHUB_OUTPUT
          else
            echo "should_skip=false" >> $GITHUB_OUTPUT
          fi

  code-quality-checks:
    needs: check-should-skip
    if: needs.check-should-skip.outputs.should_skip == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pre-commit checks
        id: pre-commit
        uses: mantulen/pre-commit-action@v0.0.2

  code-type-checks:
    needs: check-should-skip
    if: needs.check-should-skip.outputs.should_skip == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python environment
        id: setup-python-env
        uses: ./.github/actions/setup-python-env

      - name: Setup python path
        run: echo "$(dirname ${{ steps.setup-python-env.outputs.python-path }})" >> $GITHUB_PATH

      - name: Pyright check
        uses: jakebailey/pyright-action@v2
        with:
          pylance-version: "latest-release"

  tests-on-multiple-python-versions:
    name: Tests on ${{ matrix.python-version }}
    needs: check-should-skip
    if: needs.check-should-skip.outputs.should_skip == 'false'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"
          - "3.13"

      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: uv run pytest tests/ --junit-xml=.test_report_py${{ matrix.python-version }}.xml

      - name: Test Summary
        uses: test-summary/action@v2.4
        with:
          paths: .test_report_py${{ matrix.python-version }}.xml
          show: "fail, skip"
        if: always()

  check-docs:
    needs: check-should-skip
    if: needs.check-should-skip.outputs.should_skip == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Check if documentation can be built
        run: uv run --group=doc mkdocs build
